### ISSUE TITLE
Runtime error when using parallel computation

### ISSUE THREAD

**Issue by asmadotgh** [tensorflow/tcav#54]
When running TCAV with run_parallel=True, multiple workers try to write to the same file simultaneously which results in run-time errors. 
Thank you for your consideration.

**Comment by BeenKim** [comment]
What is your error exactly? This typically happens if you don't have enough RAM or CPU power to run too many jobs at once. I recommend running one job, and one job only and estimate the resources you need, then calculate the example number of jobs you have (return from https://github.com/tensorflow/tcav/blob/1d0758713c3eaf404fdd8bf2bb914a76c4813c87/tcav/utils.py#L54) and double check that you have the resources.

**Comment by asmadotgh** [comment]
Thank you very much for your response. The error is: 
`NotFoundError: Poisoned file handle: file=[file id], state=DELETED; close on [path to activation file]. `

The problem only happens when the run_parallel is true which is different from the default setting:
https://github.com/tensorflow/tcav/blob/1d0758713c3eaf404fdd8bf2bb914a76c4813c87/tcav/tcav.py#L192
and the acts_dir is not None in the activation generator class:
https://github.com/tensorflow/tcav/blob/1d0758713c3eaf404fdd8bf2bb914a76c4813c87/tcav/activation_generator.py#L95

In my case, the same random concepts are being used for calculating multiple cav s and it appears multiple processes try to write to the same file during: 
https://github.com/tensorflow/tcav/blob/1d0758713c3eaf404fdd8bf2bb914a76c4813c87/tcav/tcav.py#L247

By setting run_parallel=False, or skipping saving the activations by setting acts_dir=None the run finishes successfully given the same resources. My guess is putting some semaphores/locks/temp files while writing the activations would solve this?

Thank you!

**Comment by BeenKim** [comment]
Hi Asma, 

I don't think this is an issue with TCAV but perhaps the files that you were trying to open? If you found a resolution, please reopen this issue.
