### ISSUE TITLE
Difficulties with saved model format

### ISSUE THREAD

**Issue by lkreiskoether** [tensorflow/tcav#61]
Hi all,

Currently I'm running into some difficulties using the TCAV framework for models based on the saved model format. When I use models stored and loaded using the h5 or frozen graph format all experiments work fine. When I then try to conduct experiments based on models stored and loaded with the saved model format there arise some issues. 

First problem is that the loaded graph seems to be missing some operations of specific types such as "MaxPool" or "Reshape" which you could use as bottleneck layer with h5 or frozen graph models. After adapting the code to the loaded graph by changing the layer types/names I get an exception "tensorflow.python.framework.errors_impl.FailedPreconditionError [...]". Based on that I tried to implement some workarounds which unfortunately didn't solve the problem so far.

Did anyone had similar problems and managed to use models based on the saved model format for the TCAV framework?

Thanks!

**Comment by lkreiskoether** [comment]
Hi again,

are there any updates regarding this problem? Could anyone use models stored in the saved model format for the TCAV framework?

Thank you in advance!

**Comment by jameswex** [comment]
@BeenKim any input?

**Comment by BeenKim** [comment]
@lkreiskoether I haven't seen this issue before, but believe that this is problem with tensorflow rather than TCAV. Are you able to load up the graph *without* TCAV and do a inference? If so, please feel free reopen and share a reproducible code (if you can) and we'll look int it. If not, I recommend posting the issue to stackoverflow for (more prompt) help!
