### ISSUE TITLE
How to reproduce results for Apron, School Bus, Ping pong ball?

### ISSUE THREAD

**Issue by drishyamlabs** [tensorflow/tcav#82]
Hi,

Thanks a lot for the example code. I am particularly interested in reproducing results for the cases where concepts are coming for protected attributes like- gender, race etc. I tried the 'Apron' example using the gender information from an open source face data set . I am not really sure how the concepts for gender and race should look like and what is the number and size) of images to be taken to reproduce the results. Kindly guide me with the process as I am not getting intuitive results as shown in the paper. 

Thanks in advance.

**Comment by BeenKim** [comment]
Hello, 

Thank you for this message. 

For race and gender, we used randomly selected images (roughly 150 IIRC) from http://vis-www.cs.umass.edu/lfw/. The results will differ depending on which model you use too and how many random experiments you are doing. Unfortunately we aren't able to open source the model we used, or the exact sampled data due to license issues (since we don't own lfw). For # random experiments, you just need to do enough to pass the statistical testing. Hope this is helpful!
